services:

  # --------------------------------------------------------------------------
  # Workspace Utilities Container
  # --------------------------------------------------------------------------

  workspace:
    container_name: crb_dock_workspace
    build:
      context: ./workspace
      args:
        - PGID=${WORKSPACE_PGID}
        - PUID=${WORKSPACE_PUID}
        - TZ=${WORKSPACE_TIMEZONE}
        - INSTALL_CARGO=${WORKSPACE_INSTALL_CARGO}
        - INSTALL_SSH=${WORKSPACE_INSTALL_SSH}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APPLICATION}:${APPLICATION_LOCATION}:z
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    networks:
      - internal

  # --------------------------------------------------------------------------
  # PHP-FPM Container
  # --------------------------------------------------------------------------

  php-fpm:
    container_name: crb_dock_php
    build:
      context: ./php-fpm
      args:
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
        - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
        - INSTALL_GD=${PHP_FPM_INSTALL_GD}
        - INSTALL_IMAGICK=${PHP_FPM_INSTALL_IMAGICK}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_IONCUBE=${PHP_FPM_INSTALL_IONCUBE}
        - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_WKHTMLTOPDF=${PHP_FPM_INSTALL_WKHTMLTOPDF}
        - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
        - INSTALL_SSH=${PHP_INSTALL_SSH}
        - http_proxy
        - https_proxy
        - no_proxy
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes:
      - ${APPLICATION}:${APPLICATION_LOCATION}:z
      - ${PHP_FPM_PATH}${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
      - "9001"
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - internal

  # --------------------------------------------------------------------------
  # Redis Server Container
  # --------------------------------------------------------------------------

  redis:
    container_name: crb_dock_redis
    build:
      context: ./redis
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - internal

  # --------------------------------------------------------------------------
  # Caddy Server Container
  # --------------------------------------------------------------------------

  caddy:
    container_name: crb_dock_caddy
    build:
      context: ./caddy
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APPLICATION}:${APPLICATION_LOCATION}:z
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "${CADDY_HTTP_PORT}:8080"
      - "${CADDY_HTTPS_PORT}:8443"
    depends_on:
      - workspace
    networks:
      - internal

  # --------------------------------------------------------------------------
  # MariaDB Container
  # --------------------------------------------------------------------------

  mariadb:
    container_name: crb_dock_mariadb
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d:Z
    depends_on:
      - workspace
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - internal

  # --------------------------------------------------------------------------
  # Portainer
  # --------------------------------------------------------------------------

  # portainer:
  #   container_name: crb_dock_portainer
  #   image: portainer/portainer-ce
  #   command: -H unix:///var/run/docker.sock
  #   ports:
  #     - "${PORTAINER_WEB_PORT}:9000"
  #     - "${PORTAINER_API_PORT}:8000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ${DATA_SAVE_PATH}/portainer:/data
  #   networks:
  #     - internal

# --------------------------------------------------------------------------
# Networks Setup
# --------------------------------------------------------------------------

networks:
  internal:
    driver: "bridge"
volumes:
  mariadb_data:
  redis_data:
  caddy_data:
  caddy_config:
